### ISSUE TITLE
Example of using code

### ISSUE THREAD

**Issue by jasonjb82** [openownership/indonesia-bods-mapping#1]
Hi @stevenday 

First of all,  great work coming up with the code to map out the Indonesian Beneficial ownership which I think will be extremely useful for understanding the complex and interlinked relationships of companies there. 

I am trying to use the code (I have code.js installed) to pull data from AHU but cannot seem to find anything at the [API link](https://panduan.ahu.go.id/api/detail.php) you have on the page.

Do you have any examples I could use to run the code and pull some data from there? 

Thank you!

**Comment by stevenday** [comment]
Hi @jasonjb82 - thanks for pointing out the broken link. I've fixed that now with a link to the more generic API documentation homepage: https://panduan.ahu.go.id/api/ from where you can see the beneficial ownership endpoint (at the bottom) amongst the others offered.

However, I'm afraid we don't know anything about actually getting access to the API. We're not sure whether it's possible for non-Indonesians, or even the general public (vs specially authorised entities). The code has been developed based on the example data available on the API documentation, we don't have any other access. Our general assumption is that it will be restricted, since they charge even for regular web searches of company data: https://panduan.ahu.go.id/doku.php?id=perseroan

We're trying to get more information from the Indonesian authorities on this and if we do find out it's publicly available, we'll update the docs on this repo. Sorry I can't be of more help.

**Comment by jasonjb82** [comment]
Hi @stevenday thanks for getting back to me on this and explaining the status of the repo and the limitations of it. I really appreciate it. I understand it will be quite a challenge to have access to this information and I will keep an eye on the repo for any updates. 

Happy holidays!
